export const CART_ADD_ITMES = "CART_ADD_ITMES";
export const CART_REMOVE_ITEMS = "CART_REMOVE_ITEMS";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
