export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const CREATE_DETAILS_REQUEST = "CREATE_DETAILS_REQUEST";
export const CREATE_DETAILS_SUCCESS = "CREATE_DETAILS_SUCCESS";
export const CREATE_DETAILS_FAIL = "CREATE_DETAILS_FAIL";

export const CREATE_PAY_REQUEST = "CREATE_PAY_REQUEST";
export const CREATE_PAY_SUCCESS = "CREATE_PAY_SUCCESS";
export const CREATE_PAY_FAIL = "CREATE_PAY_FAIL";
export const CREATE_PAY_RESET = "CREATE_PAY_RESET";

export const CREATE_MY_ORDERS_REQUEST = "CREATE_MY_ORDERS_REQUEST";
export const CREATE_MY_ORDERS_SUCCESS = "CREATE_MY_ORDERS_SUCCESS";
export const CREATE_MY_ORDERS_FAIL = "CREATE_MY_ORDERS_FAIL";
export const CREATE_MY_ORDERS_RESET = "CREATE_MY_ORDERS_RESET";
